/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "STELLAR_SERVER_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}